# Dealing With Duplicate Values

In [1]:
import pandas as pd

In [11]:
cities = ['New York', 'Los Angeles', 'Chicago', 'Austin', 'Phoenix', 'Los Angeles', 'Chicago']
rankings = [1,2,3,4,5,6,7]
data = [9.8, 9.5, 9.2, 8.7, 8.5, 8.2, 8.1]

dict = {'City' : cities, 'Ranking' : rankings, 'Rating': data}

data_frame = pd.DataFrame(dict)

In [12]:
data_frame

          City  Ranking  Rating
0     New York        1     9.8
1  Los Angeles        2     9.5
2      Chicago        3     9.2
3       Austin        4     8.7
4      Phoenix        5     8.5
5  Los Angeles        6     8.2
6      Chicago        7     8.1

In [7]:
data_frame.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [8]:
data_frame.duplicated().sum()

0

In [13]:
data_frame.duplicated('City').sum()

2

In [16]:
data_frame.drop_duplicates('City', keep = 'first')

          City  Ranking  Rating
0     New York        1     9.8
1  Los Angeles        2     9.5
2      Chicago        3     9.2
3       Austin        4     8.7
4      Phoenix        5     8.5

- keep = last

In [17]:
data_frame.drop_duplicates('City', keep = 'last')

          City  Ranking  Rating
0     New York        1     9.8
3       Austin        4     8.7
4      Phoenix        5     8.5
5  Los Angeles        6     8.2
6      Chicago        7     8.1

- keep = False

In [18]:
data_frame.drop_duplicates('City', keep = False)

       City  Ranking  Rating
0  New York        1     9.8
3    Austin        4     8.7
4   Phoenix        5     8.5