In [1]:
import pandas as pd
from scipy.stats import binom

`Calculating the probability of number of questions correct from 20 questions using probability mass function`

In [4]:
num_of_questions = 20
prob_correct =0.25

In [5]:
questions = [i for i in range(1,num_of_questions+1)]

In [7]:
df = pd.DataFrame(questions)

In [10]:
df = df.rename(columns = {0 : 'num_of_correct_ques'})

`Defining the lambda function for probability calculation`

In [26]:
probability = lambda x : binom.pmf(x, num_of_questions, prob_correct)

In [14]:
df

    num_of_correct_ques
0                     1
1                     2
2                     3
3                     4
4                     5
5                     6
6                     7
7                     8
8                     9
9                    10
10                   11
11                   12
12                   13
13                   14
14                   15
15                   16
16                   17
17                   18
18                   19
19                   20

In [27]:
df['probability'] = df['num_of_correct_ques'].apply(probability)

In [28]:
df

    num_of_correct_ques   probability
0                     1  2.114141e-02
1                     2  6.694781e-02
2                     3  1.338956e-01
3                     4  1.896855e-01
4                     5  2.023312e-01
5                     6  1.686093e-01
6                     7  1.124062e-01
7                     8  6.088669e-02
8                     9  2.706075e-02
9                    10  9.922275e-03
10                   11  3.006750e-03
11                   12  7.516875e-04
12                   13  1.541923e-04
13                   14  2.569872e-05
14                   15  3.426496e-06
15                   16  3.569266e-07
16                   17  2.799425e-08
17                   18  1.555236e-09
18                   19  5.456968e-11
19                   20  9.094947e-13